"""Remove qulification unique constraint

Revision ID: 1bdf74b23927
Revises: a9c7f0b244b3
Create Date: 2025-03-06 22:35:49.703877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdf74b23927'
down_revision = 'a9c7f0b244b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_qualification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_qualification', ['qualification'], unique=1)

    # ### end Alembic commands ###
