"""pre requisite groups join condition

Revision ID: 5bb1169c0543
Revises: f601e8d4dfca
Create Date: 2025-03-10 21:30:28.580467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb1169c0543'
down_revision = 'f601e8d4dfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('prerequisite_groups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_groups', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('group_prerequisites')
    # ### end Alembic commands ###
