"""course form

Revision ID: 642041bfcceb
Revises: 80c99058e00e
Create Date: 2025-03-09 22:37:32.838918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642041bfcceb'
down_revision = '80c99058e00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('prerequisite', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('duration')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
