"""group

Revision ID: 80c99058e00e
Revises: 90172591d49b
Create Date: 2025-03-07 01:25:53.976088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c99058e00e'
down_revision = '90172591d49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite', sa.String(length=100), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('prerequisite')

    # ### end Alembic commands ###
