"""group

Revision ID: 90172591d49b
Revises: 1bdf74b23927
Create Date: 2025-03-07 01:23:55.455397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90172591d49b'
down_revision = '1bdf74b23927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('standard', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
