"""course removed

Revision ID: d5f10788f5ff
Revises: 5bb1169c0543
Create Date: 2025-03-11 00:28:07.943945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f10788f5ff'
down_revision = '5bb1169c0543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('duration', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prerequisite_courses', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('duration')
    )
    # ### end Alembic commands ###
