"""Group Course

Revision ID: f601e8d4dfca
Revises: 642041bfcceb
Create Date: 2025-03-10 03:25:34.790005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f601e8d4dfca'
down_revision = '642041bfcceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prerequisite_courses', sa.String(length=100), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('prerequisite')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite_groups', sa.String(length=100), nullable=True))
        batch_op.drop_column('prerequisite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('prerequisite_groups')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prerequisite', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('prerequisite_courses')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
